/**
 * Sitemap generation.
 *
 * Blog posts live in Supabase but the sitemap was a hand-maintained XML file,
 * last stamped 2026-04-24 and listing six posts. New articles stayed invisible
 * to crawlers until someone remembered to edit XML by hand — so they mostly
 * didn't get indexed.
 *
 * This reads the static routes from the shared manifest and the published blog
 * posts from the database, then writes public/sitemap.xml. Run before build
 * (wired into `npm run build`).
 *
 * If Supabase is unreachable — offline, missing env — it keeps the blog URLs
 * already present in the existing sitemap rather than silently dropping them.
 * A build should never quietly shrink the sitemap.
 */
import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const SITEMAP = join(ROOT, "public", "sitemap.xml");
const SITE_URL = "https://thenilgiriroot.com";

const today = new Date().toISOString().slice(0, 10);

// ---------- env ----------

async function loadEnv() {
  const envPath = join(ROOT, ".env");
  if (!existsSync(envPath)) return {};
  const out = {};
  for (const line of (await readFile(envPath, "utf8")).split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i);
    if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  return out;
}

// ---------- static routes ----------

async function loadStaticRoutes() {
  const src = await readFile(join(ROOT, "src", "data", "routes.ts"), "utf8");

  const core = [...src.matchAll(/\{\s*path:\s*"([^"]+)",\s*priority:\s*([\d.]+),\s*changefreq:\s*"(\w+)"/g)].map(
    (m) => ({ path: m[1], priority: Number(m[2]), changefreq: m[3] }),
  );

  const slugBlock = src.match(/export const LANDING_SLUGS = \[([\s\S]*?)\] as const;/);
  const landing = slugBlock
    ? [...slugBlock[1].matchAll(/"([^"]+)"/g)].map((m) => ({
        path: `/${m[1]}`,
        priority: 0.8,
        changefreq: "monthly",
      }))
    : [];

  return [...core, ...landing];
}

// ---------- blog posts ----------

async function fetchBlogPosts(env) {
  const url = env.VITE_SUPABASE_URL || env.SUPABASE_URL;
  const key = env.VITE_SUPABASE_PUBLISHABLE_KEY || env.SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) {
    console.warn("  Supabase credentials not found — keeping existing blog URLs.");
    return null;
  }

  try {
    const endpoint =
      `${url}/rest/v1/blog_posts` +
      `?select=slug,updated_at,published_at&published=eq.true&order=published_at.desc`;

    const res = await fetch(endpoint, {
      headers: { apikey: key, Authorization: `Bearer ${key}` },
      signal: AbortSignal.timeout(20_000),
    });

    if (!res.ok) {
      console.warn(`  Supabase returned ${res.status} — keeping existing blog URLs.`);
      return null;
    }

    const rows = await res.json();
    if (!Array.isArray(rows)) return null;

    return rows
      .filter((r) => r.slug)
      .map((r) => ({
        path: `/blog/${r.slug}`,
        priority: 0.6,
        changefreq: "monthly",
        lastmod: (r.updated_at || r.published_at || today).slice(0, 10),
      }));
  } catch (err) {
    console.warn(`  Could not reach Supabase (${err.message}) — keeping existing blog URLs.`);
    return null;
  }
}

/** Blog URLs already in the committed sitemap, used when the DB is unreachable. */
async function existingBlogUrls() {
  if (!existsSync(SITEMAP)) return [];
  const xml = await readFile(SITEMAP, "utf8");
  return [...xml.matchAll(/<loc>([^<]*\/blog\/[^<]*)<\/loc>/g)].map((m) => ({
    path: m[1].replace(SITE_URL, ""),
    priority: 0.6,
    changefreq: "monthly",
    lastmod: today,
  }));
}

// ---------- write ----------

const env = await loadEnv();
const staticRoutes = await loadStaticRoutes();

let blog = await fetchBlogPosts(env);
let blogSource = "Supabase";
if (blog === null) {
  blog = await existingBlogUrls();
  blogSource = "existing sitemap (fallback)";
}

const all = [...staticRoutes.map((r) => ({ ...r, lastmod: today })), ...blog];

const body = all
  .map(
    (r) => `  <url>
    <loc>${SITE_URL}${r.path === "/" ? "/" : r.path}</loc>
    <lastmod>${r.lastmod}</lastmod>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority.toFixed(1)}</priority>
  </url>`,
  )
  .join("\n\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand.
     Static routes come from src/data/routes.ts, blog posts from Supabase. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">

${body}

</urlset>
`;

await writeFile(SITEMAP, xml, "utf8");

console.log(
  `  sitemap.xml: ${all.length} URLs ` +
    `(${staticRoutes.length} static, ${blog.length} blog from ${blogSource})`,
);
