// Originally generated by Lovable. Edited to add configuration guards — see
// below. If this file is ever regenerated, re-apply that change.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as
  | string
  | undefined;

/** True when both values are present, so callers can degrade deliberately. */
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  // Loud, once, with the fix — rather than a stack trace from deep inside the
  // SDK that gives no clue which variable is missing.
  console.error(
    "[supabase] Missing configuration. Set VITE_SUPABASE_URL and " +
      "VITE_SUPABASE_PUBLISHABLE_KEY in .env (see .env.example). " +
      "Blog, forms and consent logging will not work until you do.",
  );
}

/**
 * `createClient` throws synchronously if the URL is undefined. Because this
 * module is imported at the top of several pages, that turned a missing
 * environment variable into a whole-page crash: /blog rendered the
 * ErrorBoundary fallback instead of its own "no articles" empty state, and the
 * prerenderer baked that error message into the shipped HTML.
 *
 * Passing syntactically valid placeholders keeps construction from throwing.
 * Requests then fail as ordinary network errors, which every call site already
 * handles — so a misconfigured environment degrades to "this section is
 * unavailable" instead of taking the page down. `isSupabaseConfigured` lets
 * callers skip the request entirely where a cleaner empty state is possible.
 */
export const supabase = createClient<Database>(
  SUPABASE_URL || "https://unconfigured.supabase.co",
  SUPABASE_PUBLISHABLE_KEY || "unconfigured",
  {
    auth: {
      storage: typeof window !== "undefined" ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
